---
micronaut:
  application:
    name: github-scraper
  http:
    services:
      github:
        urls:
          - "https://api.github.com/"
  caches:
    github-projects-and-stars:
      expireAfterWrite: 30s
      maximumSize: 1