spring:
  cache:
    caffeine:
      spec: "maximumSize=1, expireAfterWrite=30s"
  cloud:
    discovery:
      client:
        simple:
          instances:
            github:
              - uri: https://api.github.com
